name: my_e_m_a_i_l
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Pacotes atualizados
  app_links: ^6.4.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  collection: ^1.19.1
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.2
  font_awesome_flutter: ^10.7.0
  from_css_color: ^2.0.0
  percent_indicator: ^4.2.2  # (verifique no pub.dev a versão mais recente)
  functions_client: ^2.3.2
  go_router: ^10.1.2  # ou uma versão que você usava antes sem erro
  google_fonts: ^6.1.0
  gotrue: ^2.8.4
  hive: ^2.2.3
  intl: ^0.20.2
  json_path: ^0.7.2
  lottie: ^2.7.0
  page_transition: ^2.1.0
  path_provider: ^2.1.2
  postgrest: ^2.1.4
  provider: ^6.1.2
  realtime_client: ^2.2.1
  rxdart: ^0.27.7
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.3+1
  sqflite_common: ^2.5.4+3
  storage_client: ^2.0.3
  supabase: ^2.3.0
  supabase_flutter: ^2.6.0
  timeago: ^3.7.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0

  # Compatibilidades manuais (módulos internos de alguns pacotes)
  app_links_platform_interface: ^2.0.2
  cached_network_image_platform_interface: ^4.1.1
  cached_network_image_web: ^1.3.1
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.4.0
  path_provider_linux: ^2.2.1
  path_provider_platform_interface: ^2.1.2
  path_provider_windows: ^2.3.0
  shared_preferences_android: ^2.3.2
  shared_preferences_foundation: ^2.5.2
  shared_preferences_linux: ^2.4.1
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.2
  shared_preferences_windows: ^2.4.1
  sign_in_with_apple_platform_interface: ^1.1.0
  sign_in_with_apple_web: ^2.1.0
  url_launcher_android: ^6.3.10
  url_launcher_ios: ^6.3.1
  url_launcher_linux: ^3.2.0
  url_launcher_macos: ^3.2.1
  url_launcher_platform_interface: ^2.3.2
  url_launcher_web: ^2.3.3
  url_launcher_windows: ^3.1.2
  webview_flutter_android: ^3.16.7
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_wkwebview: ^3.15.0

  cupertino_icons: ^1.0.6

dependency_overrides:
  http: ^1.2.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  image: ^4.2.0
  lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: '#f9f9f9'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

